version: "3"
services:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: ./cn_api
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
      - '/project/tmp'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  cn_api:
    build: ./cn_api
    command: bash -c "rm -f /cn_api/tmp/pids/server.pid && foreman start -f /cn_api/Procfile"
    environment:
      - PORT=3000
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
    volumes:
      - ./cn_api:/cn_api
      - rails_log:/cn_api/log
    ports:
      - "3030:3000" # use port that you want to in your local instead of 3091
    depends_on:
      - db
      - redis

  cn_front:
    build: ./cn_front
    ports:
      - "8091:8080" # use port that you want to in your local instead of 8091
    volumes:
      - ./cn_front:/cn_front
      - front_node_modules:/cn_front/node_modules

volumes:
  db:
  rails_log:
  redis:
  front_node_modules: